f1:
  exposure:
    properties:
      url2: https://localhost
      url: https://f1exposure.com
      saveRadioLocation: C:\root\
      twitterDebug: false
      twitterKey: eCF9Xm6wa5brKSAxOhFS4FpXP
      twitterSecret: hkjZw8YFhRDLjL3yVuUgxwF5DRKgyQ7ZuNscQMJgr8fA9ycCPI
      twitterAccessToken: 2307261354-VCg4IcH8xOjbv6NhlMfYtO7kA2z5tbp7Bo7xBWf
      twitterAccessTokenSecret: I56TyVDo9GVw0s9WfyMuyZt2K9tGrb4XAVO2wax8RKFbs
      twitterClientId: a1BIb1BUYVlyVnB6ejM2bzQ4QVQ6MTpjaQ
      twitterClientSecret: BEh2qOmAp0jRJHEfjh71fcgX5yJ7BC2uM0p4OqHKk2PP8y-88I
      twitterKey_duke: eCF9Xm6wa5brKSAxOhFS4FpXP
      twitterSecret_duke: hkjZw8YFhRDLjL3yVuUgxwF5DRKgyQ7ZuNscQMJgr8fA9ycCPI
      twitterAccessToken_duke: 2307261354-VCg4IcH8xOjbv6NhlMfYtO7kA2z5tbp7Bo7xBWf
      twitterAccessTokenSecret_duke: I56TyVDo9GVw0s9WfyMuyZt2K9tGrb4XAVO2wax8RKFbs
      twitterKey_f1ex: Oh4Fq09DPxIvy6FmVH76mcj0v
      twitterSecret_f1ex: ZcpC4aVpIee4euvZF4IiAHzlYY06VpI22kKfroX6Cxe5u7uBgC
      twitterAccessToken_f1ex: 1530482716990394368-E0efMcIWH4IT2lsfzTjqUCClf8rtWq
      twitterAccessTokenSecret_f1ex: 41DI3NKWO4NX2FYv0S4yC9hoI9Iap8Dxn7ohRBJX8e48g
      newTwitterClientID_Duke: a1BIb1BUYVlyVnB6ejM2bzQ4QVQ6MTpjaQ
      newTwitterClientSecret_Duke: BEh2qOmAp0jRJHEfjh71fcgX5yJ7BC2uM0p4OqHKk2PP8y-88I
      instagramWorkerUsername: npc3422
      instagramWorkerPassword: "qwadrat1"
      instagramWorker2Username: miroslav.dragicevic1
      instagramWorker2Password: "qwadrat1234"
      instagramOfficialUsername: f1exposure
      instagramOfficialPassword: "!qwadrat"
      calendarUrl: https://www.formula1.com/calendar/Formula_1_Official_Calendar.ics
      sportSurgeRoot: https://api.sportsurge.net/events/list?group=13
      sportSurgeStreams: https://api.sportsurge.net/streams/list?event=
      formula1RacingUrl: https://www.formula1.com/en/racing/
      replaysUrl: https://f1hd.net/
      howManySeasonsBack: 6
      admins:
        - fb26e2db-da1b-462e-aeea-fec3955b3e40
        - sorimsquare33
      clients:
        - 36aed15c-f2ca-40a0-ae6d-96d82091df99
        - 7c36a15a-019a-4c36-944d-c63423480ca5
server:
  compression:
    enabled: true
    mime-types: application/javascript,text/javascript
  error:
    whitelabel:
      enabled: false
  port: 443
  http-port-to-redirect: 80
  ssl:
    key-store: /root/keystore.p12
    key-store-password: password
    key-store-type: pkcs12
    key-alias: f1exposure
    key-password: password
spring:
  application:
    name: f1-exposure-rest-api
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  datasource:
    f1-exposure:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/postgres?currentSchema=f1exposure
      username: postgres
      password: postgres
      auto-commit: true
      connection-timeout: 1000
      idle-timeout: 30000
      login-timeout: 1000
      pool-name: DB-PROFILE-POOL
      maximum-pool-size: 50
      minimum-idle: 3
      query-timeout: 10000
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  liquibase:
    datasource:
      f1-exposure:
        enabled: false
        change-log: classpath:/db/liquibase-changelog.xml
        drop-first: false
        user: postgres
        password: postgres
security:
  require-ssl: true
logging:
  level:
    c.g.h.javascript.host.css.CSSStyleSheet: ERROR
  logback:
    rollingpolicy:
      max-file-size: 20MB
  file:
    name: /root/exposure_log/exposure.log
upload:
  path: /uploads-deleteme
twitter:
  accounts:
    list: formula1,SkySportsF1,fia,redbullracing,ScuderiaFerrari,Carlossainz55,Charles_Leclerc,Max33Verstappen,SChecoPerez,MercedesAMGF1,LewisHamilton,GeorgeRussell63,WilliamsRacing,alex_albon,LoganSargeant,McLarenF1,LandoNorris,OscarPiastri,AlpineF1Team,OconEsteban,PierreGASLY,visacashapprb,danielricciardo,yukitsunoda07,stakef1team_ks,ValtteriBottas,ZhouGuanyu24,HaasF1Team,KevinMagnussen,HulkHulkenberg,AstonMartinF1,alo_oficial,lance_stroll
    ferrari: ScuderiaFerrari,Carlossainz55,Charles_Leclerc

