f1:
  exposure:
    properties:
      tempo: tttejmpo
      currentYear: 2021
      twitterDebug: false
      twitterKey: eCF9Xm6wa5brKSAxOhFS4FpXP
      twitterSecret: hkjZw8YFhRDLjL3yVuUgxwF5DRKgyQ7ZuNscQMJgr8fA9ycCPI
      twitterAccessToken: 2307261354-VCg4IcH8xOjbv6NhlMfYtO7kA2z5tbp7Bo7xBWf
      twitterAccessTokenSecret: I56TyVDo9GVw0s9WfyMuyZt2K9tGrb4XAVO2wax8RKFbs
      instagramUsername: miroslav.dragicevic1
      instagramPassword: "!qwadrat1"
      calendarUrl: https://www.formula1.com/calendar/Formula_1_Official_Calendar.ics
      sportSurgeRoot: https://api.sportsurge.net/events/list?group=13
      sportSurgeStreams: https://api.sportsurge.net/streams/list?event=
      formula1RacingUrl: https://www.formula1.com/en/racing/
      howManySeasonsBack: 4
      admins:
        - fb26e2db-da1b-462e-aeea-fec3955b3e40
        - sorimsquare33
      clients:
        - 36aed15c-f2ca-40a0-ae6d-96d82091df99
        - 7c36a15a-019a-4c36-944d-c63423480ca5
server:
  port: 443
#  ssl:
#    key-store: classpath:keystore.p12
#    key-store-password: password
#    key-store-type: pkcs12
#    key-alias: springboot
#    key-password: password
spring:
  application:
    name: f1-exposure-rest-api
  datasource:
    f1-exposure:
      driver-class-name: org.postgresql.Driver
      jdbc-url: jdbc:postgresql://localhost:5432/postgres?currentSchema=f1exposure
      username: postgres
      password: postgres
      auto-commit: true
      connection-timeout: 1000
      idle-timeout: 30000
      login-timeout: 1000
      pool-name: DB-PROFILE-POOL
      maximum-pool-size: 5
      minimum-idle: 3
      query-timeout: 3000
  autoconfigure:
    exclude: >
      org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration
  liquibase:
    datasource:
      f1-exposure:
        enabled: false
        change-log: classpath:/db/liquibase-changelog.xml
        drop-first: true
        user: postgres
        password: postgres
logging:
  logback:
    rollingpolicy:
      max-file-size: 20MB
  file:
    name: E:\temp\exposure.log
    name2: /home/sorim/exposure_log/exposure.log